HAI
  I HAS A GRADE1 ITZ 2.0
  I HAS A GRADE2 ITZ 1.0
  I HAS A GRADE3 ITZ 2.75
  I HAS A UNITS1 ITZ 5.0
  I HAS A UNITS2 ITZ 3.0
  I HAS A UNITS3 ITZ 3.0
  I HAS A GWA ITZ QUOSHUNT OF SUM OF PRODUKT OF GRADE1 AN UNITS1 AN SUM OF PRODUKT OF GRADE2 AN UNITS2 AN PRODUKT OF GRADE3 AN UNITS3 AN SUM OF UNITS1 AN SUM OF UNITS2 AN UNITS3
  VISIBLE SMOOSH "GWA IS " GWA
KTHXBYE