BTW arithmetic operators

HAI

I HAS A X ITZ 5
I HAS A Y ITZ 3
I HAS A Z
VISIBLE X
X R SUM OF X AN Y
VISIBLE X BTW 8
X R DIFF OF X AN Y
VISIBLE X BTW 2
X R PRODUKT OF X AN Y
VISIBLE X BTW 15
X R QUOSHUNT OF X AN Y
VISIBLE X BTW 1.6666667
X R BIGGR OF X AN Y
VISIBLE X BTW 5
X R SMALLR OF X AN Y
VISIBLE X BTW 3

BTW Z R SUM OF X AN Y
BTW VISIBLE Z
BTW Z R DIFF OF X AN Y
BTW VISIBLE Z
BTW Z R PRODUKT OF X AN Y
BTW VISIBLE Z
BTW Z R QUOSHUNT OF X AN Y
BTW VISIBLE Z
BTW Z R BIGGR OF X AN Y
BTW VISIBLE Z
BTW Z R SMALLR OF X AN Y
BTW VISIBLE Z

BTW logical operators

I HAS A A ITZ WIN
I HAS A B ITZ FAIL
I HAS A Z

A R BOTH OF A AN B
VISIBLE A BTW FAIL
A R EITHER OF A AN B
VISIBLE A BTW FAIL
A R WON OF A AN B
VISIBLE A BTW FAIL
A R NOT B
VISIBLE A BTW WIN
A R ANY OF A AN B AN FAIL MKAY
VISIBLE A BTW WIN
A R ALL OF A AN B AN WIN MKAY
VISIBLE A BTW FAIL

BTW Z R BOTH OF A AN B
BTW VISIBLE Z
BTW Z R EITHER OF A AN B
BTW VISIBLE Z
BTW Z R WON OF A AN B
BTW VISIBLE Z
BTW Z R NOT B
BTW VISIBLE Z
BTW Z R ANY OF A AN B AN FAIL MKAY
BTW VISIBLE Z
BTW Z R ALL OF A AN B AN WIN MKAY
BTW VISIBLE Z

VISIBLE NOT B BTW WIN

BTW logical  operators

VISIBLE BOTH SAEM X AN Y    BTW X == Y
VISIBLE DIFFRINT X AN Y     BTW X != Y
VISIBLE BOTH SAEM X AN BIGGR OF X AN Y   BTW X >= Y
VISIBLE BOTH SAEM X AN SMALLR OF X AN Y  BTW X <= Y
VISIBLE DIFFRINT X AN SMALLR OF X AN Y   BTW X > Y
VISIBLE DIFFRINT X AN BIGGR OF X AN Y    BTW X < Y

I HAS A AGE ITZ 18
BTW I HAS A AGE
BTW GIMMEH AGE
BOTH SAEM AGE AN 18
O RLY?
    YA RLY
        VISIBLE "Legal"
    NO WAI
        VISIBLE "Underage"
OIC

I HAS A classification ITZ "Senior"

classification
WTF?
    OMG "Freshman"
        VISIBLE "2016"
    GTFO
    OMG "Sophomore"
        VISIBLE "2015"
    GTFO
    OMG "Junior"
        VISIBLE "2014"
    GTFO
    OMG "Senior"
        VISIBLE "2013"
    GTFO
    OMGWTF
        VISIBLE "2012 and above"
OIC

KTHXBYE
